import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { headers } from "next/headers"; // Keep headers import for now, might be needed elsewhere
import { TRPCReactProvider } from "@/trpc/react";
import { SessionProvider } from "next-auth/react";
import { BottomNavbar } from "./_components/BottomNavbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-black">
        <SessionProvider>
          <TRPCReactProvider>
            <div className="min-h-screen bg-black text-white">
              {/* Main Content */}
              <div className="mx-auto max-w-2xl px-2 py-4">{children}</div>

              <BottomNavbar />
            </div>
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
